name: taxifarefinder
description: A Dart wrapper for the TaxiFareFinder API <https://www.taxifarefinder.com/api.php>
version: 1.0.1
author: Tom Oehlrich <mail@tomoehlrich.com>
repository: https://github.com/tomoehlrich/taxifarefinder-dart
homepage: https://github.com/tomoehlrich/taxifarefinder-dart

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  http: ^0.12.0+2
  json_annotation: ^3.0.0

dev_dependencies:
  test: ^1.6.5
  build_runner: ^1.0.0
  json_serializable: ^3.2.0
  pedantic: ^1.0.0