name: taxifarefinder
description: A Dart wrapper for the TaxiFareFinder API <https://www.taxifarefinder.com/api.php>
version: 2.0.0
repository: https://github.com/tomoehlrich/taxifarefinder-dart
homepage: https://github.com/tomoehlrich/taxifarefinder-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: ^0.13.5
  json_annotation: ^4.7.0

dev_dependencies:
  build_runner: ^2.2.1
  json_serializable: ^6.4.1
  lint: ^1.0.0
  test: ^1.21.6